spring.application.name=WalletSystem

# MySQL datasource (development)
spring.datasource.url=jdbc:mysql://localhost:3306/koins_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT settings
app.jwt.secret=verysecretkeychangeme
app.jwt.expirationMs=3600000

# OTP settings
app.otp.expiration-minutes=10
app.otp.max-requests-per-hour=5

logging.level.org.springframework=INFO

